# Generated by Django 4.0.5 on 2022-10-18 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Asignatura')),
                ('nombreAsignatura', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('idClase', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de clase')),
                ('fechaClase', models.DateField(verbose_name='fecha clase')),
                ('sala', models.CharField(max_length=5, verbose_name='Numero Sala')),
                ('horario', models.CharField(max_length=30, verbose_name='Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('idSeccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Seccion')),
                ('sigla', models.CharField(max_length=3, verbose_name='Sigla de Seccion')),
                ('semestre', models.CharField(max_length=1, verbose_name='Semestre')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arQR.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arQR.seccion')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleClase',
            fields=[
                ('idDetalleClase', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de detalle clase')),
                ('estado', models.CharField(max_length=1, verbose_name='p de presente a de ausente')),
                ('rutAlum', models.CharField(max_length=10, verbose_name='Rut del alumno')),
                ('idClase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arQR.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='idSeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arQR.seccion'),
        ),
    ]
